### ISSUE TITLE
Need to create a "backup SQL system"

### ISSUE THREAD

**Issue by War3Evo** [War3Source/War3Source#112]
The system already detects when it no longer has access to the remote SQL database.  All needs to be done now is to start recording to the local database as soon as it detects the fault.   Once it regains connection, if it the server is still alive at the time it has reconnection, to merge entries from the local to the main.

It will probably need to create the time it started recording into everyone's file.

On server restart, the server can check the local database to see if it ever lost server connection to the remote SQL database.   If it did, to take the data from the local and merge it to the main SQL server, then zero out or delete the entries in the local database.

If the database in the local is too big to merge into the main, it may be best to do these activities during a set time or on startup.

**Comment by necavi** [comment]
If anyone still has interest in doing this: Setup a local MySQL instance on the gameserver, send data there and have it synced with an external MySQL instance.
