### ISSUE TITLE
Playing custom sounds

### ISSUE THREAD

**Issue by DonRevan** [War3Source/War3Source#157]
We currently put all War3Source sounds in the `gameDir/sounds/music` directory in order to be able to play sounds in CS:GO.
However, this is not recommended because they're tied to the game's music volume.
For more information read this: https://wiki.alliedmods.net/CSGO_Quirks#Playing_Custom_Sounds

We should switch to fake precaching them.

**Comment by BrutalCSEjziponken** [comment]
Is this fixed? Just made a War3 server and it was full in like 5 min. Great mod but it has some bugs. :/

**Comment by DonRevan** [comment]
No its not. Sorry, I'm too busy currently to start working on this.

**Comment by BrutalCSEjziponken** [comment]
Not sure if this helps: https://forums.alliedmods.net/showthread.php?t=269792

**Comment by DonRevan** [comment]
Okay, this should be fixed - please reopen if you experience any problems!
