### ISSUE TITLE
[CS:GO][BUG]  Anhk of reincarnation permits weapon respawn in second-half pistolround

### ISSUE THREAD

**Issue by spasaintk** [War3Source/War3Source#163]
Items such as Anhk of reincarnation and mole are not being cleared during half-time where the teams are swapped. This has as effect that players end up carrying normal weapons during the pistol round. Half-time should be threaded as if the map had just loaded as player money etc. is being reset at that time as well.

Plugin version: "War3Source" (2.J231) by War3Source Team
SourceMod Version: 1.6.2-dev+4566
Metamod:Source version 1.10.3-dev Build ID: 915:5926f92

OS: Linux

**Comment by necavi** [comment]
What exactly is the issue with Mole? It does not give them a weapon of any sort. I'm disinclined to stop them from moling simply because it costs a large amount of money due to it being a normal racial ability (warden and a few others, if I recall correctly). 

I'm changing Ankh to ignore the first round after half-time.

**Comment by Advkt** [comment]
Ankh still activates on half-time pistol round, it seems.

 I chucked in a debug message to tell me when the start_halftime event fired but it doesn't seem to trigger at halftime.

**Comment by DonRevan** [comment]
Correct event name should be "announce_phase_end" but I'm not really sure if this works.
Round-state is reset on round_start, RS is set to RS_First on halftime. This means we expect announce_phase_end to fire after round_start, is this the case?

**Comment by Advkt** [comment]
announce_phase_end fires after round_end in the final round of the first half, from what I can tell from display_game_events

round_announce_last_round_half also fires in the last round just at the start of it. Not sure of the order regarding it though.

**Comment by necavi** [comment]
I'm afraid I was doing it without a copy of CS:GO setup and made a few guesses, I'll look into it more directly later today.

**Comment by SHAREN** [comment]
http://war3source.com/index.php?topic=2368.0 I understand very little English, just leave it here
