### ISSUE TITLE
Chronos ultimate not blocking damage

### ISSUE THREAD

**Issue by DonRevan** [War3Source/War3Source#188]
Copied from pull request #187 

Players receiving bullet,rocket etc damage when should be only melee..

see here: https://github.com/War3Source/War3Source/blob/master/addons/sourcemod/scripting/War3Source_014_Chronos.sp#L393
Should use War3_IsMeleeWeapon instead

while we're at it -- maybe remove W3IsDamageFromMelee?

EDIT (29/06/2015):
I just noticed that if the player throws a grenade and switches to the knife before it explodes it can actually deal damage to players that are trapped inside of the bubble. Can we use another hook for this so we dont use W3GetCurrentWeaponEnt()?

**Comment by derekl7** [comment]
someone needs to debug which weapon is passing the is weapon melee check
