### ISSUE TITLE
Levelbank chat spam

### ISSUE THREAD

**Issue by ice-mann** [War3Source/War3Source#192]
After a player uses levelbank, They still receive  [War3Source]  You have 10 levels in your levelbank, say levelbank to use them in chat message.

**Comment by necavi** [comment]
Do you mean after a player types "levelbank" at all, or once the levels are used?

**Comment by mipek** [comment]
If a player has used atleast 1 level from the levelbank and the CVar war3_print_levelbank_spawn is set to 2 no message will be shown.
