### ISSUE TITLE
entity crash, need help.

### ISSUE THREAD

**Issue by DraxB** [War3Source/War3Source#198]
Hi I've run across an issue. When i try to use the blood mages ultimate flamestrike my server crashes with this message.

ERROR: Tried to SetParentAttachment for entity info_particle_system (info_particle_system), but it has no attachment named rfoot.

Any help would be highly appreciated. Its on csgo with the newest version of sourcemod.

**Comment by DonRevan** [comment]
This is probably related to the new player models/hitboxes. I'll take a look

**Comment by DraxB** [comment]
Yeah I thought the same, I really appreciate these fast responses. Thank you for the help! :)

**Comment by DonRevan** [comment]
The problem was that War3Source tried to delete the entity at index 0(which is the world entity) - Fixed now!
As you mentioned, there was a problem with the effects as well so I redid the ultimate effect :)
Only thing missing now is a sound for the ultimate.
