### ISSUE TITLE
Spaming in server concole "SV_StartSound: music/war3source/csgo/ui/hint.mp3 not precached (0)"

### ISSUE THREAD

**Issue by SHAREN** [War3Source/War3Source#199]
https://github.com/War3Source/War3Source/search?utf8=%E2%9C%93&q=csgo%2Fui%2Fhint&type=Code there may be a bug?

**Comment by DonRevan** [comment]
What version are you using? I thought this was already fixed by https://github.com/War3Source/War3Source/issues/194 :question:

**Comment by SHAREN** [comment]
oh sorry, somehow I missed that time Engine_Hint
