### ISSUE TITLE
[Request + possible noclip bug]

### ISSUE THREAD

**Issue by DraxB** [War3Source/War3Source#202]
Hi again,

The request:
I've been setting up my server with war3source, and I was looking for a command to reset the EXP for all players. I haven't been able to find one, if such a command exist it would be nice if you could tell me the name of it, if not I would highly appreciate if such thing could be made. The reason I'm asking for such command, is because I'm from a bigger community and I don't get access to e.g mySQL, so I'm not able to reset it by wiping the database. 

Possible bug:
In cs:go it seems like I can't make noclip work properly when running war3source on my server. I searched for the string "noclip" in all folders and was wondering if one of the following could be the cause:

War3Source_005_BloodMage.sp:
  597              {
  598                  //PrintToChatAll("omfg remove true");
  599:                 //SetEntityMoveType(client, MOVETYPE_NOCLIP);
  600                  War3_SpawnPlayer(client);
  601                  W3EmitSoundToAll(reviveSound,client);
  ...
  661                  
  662                  fLastRevive[client]=GetGameTime();
  663:                 //test noclip method
  664                  
  665                  //SetEntityMoveType(client, MOVETYPE_WALK);

War3Source_Engine_BuffSpeedGravGlow.sp:
  415                      shouldmoveas=MOVETYPE_NONE;
  416                  }
  417:                 if(W3GetBuffHasTrue(client,bNoClipMode)){
  418:                     shouldmoveas=MOVETYPE_NOCLIP;
  419                  }
  420                  else if(W3GetBuffHasTrue(client,bFlyMode)&&!W3GetBuffHasTrue(client,bFlyModeDeny)){

War3Source_Constants.inc:
  312    bFlyMode,   //fly mode
  313    bFlyModeDeny,
  314:   bNoClipMode,
  315    
  316    fArmorPhysical,
  ...
  472    
  473    
  474:   buffpropertiesarray[ bNoClipMode ][DefaultValue]=false;
  475:   buffpropertiesarray[ bNoClipMode ][BuffStackType]=bHasOneTrue;  
  476    

Thanks in advance,
DraxB.

**Comment by derekl7** [comment]
war3source manages movetype on all players, therefore any other plugin that tries to noclip will be overwritten by war3source


there is no way to set xp on all players in the database

there may be a way to set xp on all players in game using @all or whatever

**Comment by DraxB** [comment]
I see, if anyone would be able to make a command that would be appreciated. If not then this can be closed.

**Comment by DonRevan** [comment]
The noclip issue annoys me as well.
Database reset -> http://war3source.com/index.php?topic=2364.msg13229#msg13229

**Comment by necavi** [comment]
If you need a command that will properly set the movetype for individual players, request it on the forums, I can probably dig up my old War3Source_Commands project.
