### ISSUE TITLE
[Race Scout - CS:GO] Weapon + shadow still visible. 

### ISSUE THREAD

**Issue by DraxB** [War3Source/War3Source#203]
When using the vanish ability with Scout the weapon is still visible and the shadow is still visible. 

Dropbox link with demo: https://www.dropbox.com/s/ltu4eust2vgtef0/testscout.dem?dl=0

I would also like to ask do you prefer issues being posted here or on the war3source forum?

**Comment by DonRevan** [comment]
Valve broke this when they added the sv_immunity_alpha(or something like that).. I'll take a look - I think we can't set weapon color anymore but that's not a real issue because we can just force the worldmodel of the weapon to not render at all(which should have the same effect)

Reporting issues on github is better because most people will refer to github instead of having to create a extra war3source account just to report bugs.

**Comment by necavi** [comment]
We would not want to disable rendering of the weapon except on 0% visibility, otherwise it presents a major tactical advantage to a player with a low stealth amount - not being able to see if that player has a pistol or a SAW.

**Comment by necavi** [comment]
I would also strongly recommend testing that with another player, the way they added invisibility to CS:GO was very strange. All players on your team show up as fully visible except for yourself in thirdperson, but I believe that invisibility only fully works when you're looking at a player on another team.

**Comment by DonRevan** [comment]
Yes of course, scout uses a 0.03% Visibility buff so I think it's safe to change it to 0%, set RenderMode_None and call it a day. This should resolve showing the shadow as a side effect too

**Comment by DonRevan** [comment]
It isn't as easy as I thought. Even when RENDER_NONE is set weapons are still being rendered and shadows are still being displayed. Still have to test this with another player though.

If everything fails we should still be able to use a ShouldTransmit hook to achieve the desired result.

**Comment by necavi** [comment]
Yeah, shouldtransmit would be your only hope there. I'm fairly certain that shadows would not show up if another player was invisible, you could try with bots, make a simple plugin to make everyone 90% invisible. Invis has always been a bit iffy on source, considering that it is an engine-level bug that if you shine a flashlight on a 0 alpha player it ALWAYS casts a shadow.

**Comment by DonRevan** [comment]
I just tested with bots.. well, it works with teammates(no shadows, no guns) but I can still see enemy bots that should be 100% invisible - strange

**Comment by necavi** [comment]
Yeah, I'm very much not surprised. When I did the initial testing for visibility after the update I was shocked at how inconsistently everything was applied.
