### ISSUE TITLE
Update maxing races with >16 levels and awarding levels on race change.

### ISSUE THREAD

**Issue by Advkt** [War3Source/War3Source#204]
Upon switching to a race (unsure if this only happens when the race is level 0) the player is given two levels.

 After reaching level 16, upon gaining XP, races with greater than 16 levels instantly reach max level.

**Comment by necavi** [comment]
Which build are you running?

**Comment by Advkt** [comment]
This is post the latest change to the Engine_XPGold.sp. I've rolled back to an earlier version of the file which has stopped the issue from occurring. I'll just edit in our servers war3source.ini as it's modified with different values.

**Comment by necavi** [comment]
I think I know what's going on, I'll fix it in a few minutes.

**Comment by necavi** [comment]
Should be fixed now, there was a small issue with how I changed things, if you had whitespace in the string it would consider that a value. I've fixed that so now it ignores everything except for numbers.

**Comment by Advkt** [comment]
Just had a user instantly reach max level upon switching to a race. The race has 20 levels and he was level 15 before switching to it, which he did while dead. I've just updated to the latest files as of a few hours earlier.
