### ISSUE TITLE
Soul Reaper's Aura doesn't respect Skill Immunity

### ISSUE THREAD

**Issue by Advkt** [War3Source/War3Source#205]
Pretty much as the title says, Soul Reaper's "Withering Presence" ignores Skill Immunity. I'm not sure if the aura functions offer support for skill/ultimate immunity for that matter.

**Comment by derekl7** [comment]
withering presence does not have any skill immunity blocks, its a direct HP decrease, does not go through any armor

http://hon.gamepedia.com/Soul_Reaper

althought i am not sure what happens if shadow hunter has 1 hp and activates ult, i would expect war3_dealdamage to still be hooked by OnW3TakeDmgAllPre and blocked by shadow hunter

**Comment by Advkt** [comment]
The issue being that races such as Wisp, http://war3source.com/index.php?topic=462.0, instantly die from coming in contact with the aura. 

I'd argue that, while thematically appropriate for the race, some liberties could be taken for the sake of consistency in War3Source.

**Comment by DonRevan** [comment]
I agree with this. Objections?

**Comment by derekl7** [comment]
What's your proposed fix?

**Comment by DonRevan** [comment]
Withering Presence should respect skill immunity for the sake of consistency. We could do something like: all skills with magical damage can be blocked by skill immunity but I don't see Withering Presence really following a system -> why does it ignore skill immunity?

**Comment by derekl7** [comment]
It was originally superior true damage from heroes of newerth implementation. I am willing to have it respect skill immunity, but how does that solve races with 1hp problem? Are they always immune?

**Comment by DonRevan** [comment]
Yeah that would be something that the developer who creates 1hp races has to keep in mind. Not too sure if this is actually a good idea.

Another possible fix for this is to implement a "OnW3BuffApply" forward that is fired before a buff is applied so one can check if it OK to do it. This can be done as a W3Denyable too.
Something like:
```SourcePawn
//raceID is the race of the caster
forward bool OnW3BuffApply(int raceID, int client, W3Buff buff, any value); 
```
Now, when a race that wants no HPDecay to happen it can easily block the undesired buffs.

However, the easieset solution would be probably to implement something like _fHPDecayDeny_ as there already is a _fHPRegenDeny_ counterpart. Easiest is probably best.

**Comment by derekl7** [comment]
Decay deny buff is fine with me

**Comment by DonRevan** [comment]
Okay, I took a quick glance at _fHPRegenDeny_ and it doesn't look like it's actually implemented.
I'll fix this when adding the new (deny-)buff.

**Comment by derekl7** [comment]
derp...
and thanks to religious re-formatting of tabs and spaces, i can't use the blame feature correctly

**Comment by derekl7** [comment]
can you also change fHPRegenDeny to bHPRegenDeny

f prefix doesnt make sense for  stack type, buffpropertiesarray[ fHPRegenDeny][BuffStackType]=bHasOneTrue;

**Comment by DonRevan** [comment]
Is it ok to rename fHPRegenDeny to bHPRegenDeny or should we add an alias to W3Buff like
bHPRegenDeny = fHPRegenDeny in order to maintain backwards compatibility? The thing is, it's currently not working anyway so we should be able to just ignore that and rename it and avoid the source getting more dirty - what do you think?

**Comment by derekl7** [comment]
Rename it where it was, but make the backward compatible variable at the end of the enum list. It has to be inside the enum to avoid tag warnings, and last to not shift existing values
